services:
  - type: web
    name: riadda-web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_RECEIPT_HMAC_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
